project:
  type: website

website:
  title: "matthewgreenberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd
        text: Blog
      - href: https://www.linkedin.com/in/matthew-greenberg-32b91880/
        text: LinkedIn
        target: "_blank"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
